### ISSUE TITLE
Sweep: implement a memtable in LSM-Tree based AVL and the file is named memtable.go in the root of the repository

### ISSUE THREAD

**Issue by yeqown** [yeqown/go-wal#4]
> Create a new file named memtable.go in the root of the repository. In this file, define a struct for the memtable and the AVL tree. Implement methods for the memtable to insert, delete, and search for keys. Implement methods for the AVL tree to insert, delete, and search for keys, and to balance the tree after insertions and deletions. Implement a method for the memtable to flush its contents to disk when it reaches a certain size.

> Create a new file named memtable.go in the root of the repository. In this file, define a struct for the memtable and the AVL tree. Implement methods for the memtable to insert, delete, and search for keys. Implement methods for the AVL tree to insert, delete, and search for keys, and to balance the tree after insertions and deletions. Implement a method for the memtable to flush its contents to disk when it reaches a certain size.

Checklist:

- [X] `memtable.go`
> Create a new file in the root of the repository. Define a struct for the memtable with methods to insert, delete, and search for keys. Define a struct for the AVL tree with methods to insert, delete, and search for keys, and to balance the tree after insertions and deletions. Implement a method for the memtable to flush its contents to disk when it reaches a certain size.

**Comment by wwzeng1** [comment]
Hi @yeqown! I'm looking into this issue right now

**Comment by wwzeng1** [comment]
Sweep: retry

**Comment by yeqown** [comment]
Sweep: you should implement all methods not only define them
